#!/usr/bin/env python3
"""
Miaopu panel reconciler. Runs in the MAIN SYSTEM (Cowork), never in the arm.

  python3 reconcile.py inbox/panel/<RUN_ID>

Reads every FINDINGS_*.md in the run, then writes RECONCILED.md and COMPARISON.md
next to them. Works for ANY backend: it is the only component every backend shares,
which is why seat accounting (COMPARISON.md) lives here and not in a launcher. It does four things that were done by hand on run 2026-08-19_0829
and took longer than the run itself:

1. ALIAS MERGE. Chinese name, group name, subsidiary and brand are the same entity.
   Uses alias_store.json and proposes new merges it is not sure about, never merging
   silently. 77 raw headings collapsed to 31 entities on the seeding run.
2. SOURCE-INDEPENDENCE. Counts DISTINCT SOURCE DOMAINS behind an entity, not the number
   of models asserting it. Three models echoing one press article is one source, not
   triangulation (CAL-11). Anything with one domain is labelled single-source no matter
   how many models agreed.
3. PIPELINE CROSS-MATCH. Every entity is checked against exports/PIPELINE.md, archived
   rows and 中文名 included. On the seeding run only one model of three did this correctly.
4. VERIFICATION QUEUE. Emits the listed companies found, which are the ones 互动易 term
   search can actually verify. No panel model queried 互动易 on the seeding run.
5. RUBRIC COVERAGE (added 2026-09-04). Counts, per client-rubric field, how many findings
   carry a sourced value, how many say `not obtained`, and how many OMITTED the field
   entirely. The third number is the one that matters: an omitted field means the model
   never looked, a `not obtained` means it looked and Chinese disclosure is the limit.
   They read identically in a workbook cell and they are not the same fact.

It does not score, does not gate and does not write to the workbook. That is intake.md.
"""
import json, os, re, sys, collections
from urllib.parse import urlparse

HERE = os.path.dirname(os.path.abspath(__file__))

def load_aliases():
    p = os.path.join(HERE, "alias_store.json")
    d = json.load(open(p, encoding="utf-8"))
    return d["aliases"], {tuple(x) for x in d.get("never_merge", [])}

def parse_findings(path):
    t = open(path, encoding="utf-8").read()
    out = []
    blocks = re.split(r"^### ", t, flags=re.M)[1:]
    for b in blocks:
        head = b.split("\n", 1)[0].strip()
        m = re.match(r"(F-\d+)\s*[·|-]\s*(.+)", head)
        if not m:
            continue
        fid, name = m.group(1), m.group(2).strip()
        body = b
        fields = dict(re.findall(r"^-\s*([a-z_]+):\s*(.*)$", body, re.M))
        urls = re.findall(r"https?://[^\s)\]|·]+", body)
        out.append(dict(fid=fid, name=name, fields=fields,
                        urls=[u.rstrip(".,;") for u in urls], body=body))
    return out

def canon(name, aliases, unmatched_key=True):
    low = name.lower()
    for c, subs in aliases.items():
        if any(s.lower() in low for s in subs):
            return c, True
    return (name if unmatched_key else None), False

def zh(s):
    return "".join(re.findall(r"[一-鿿]+", s))

def load_pipeline():
    p = os.path.join(HERE, "exports", "PIPELINE.md")
    rows = []
    if not os.path.exists(p):
        return rows
    for line in open(p, encoding="utf-8"):
        if not line.startswith("|"):
            continue
        c = [x.strip() for x in line.strip().strip("|").split("|")]
        if len(c) > 3 and re.match(r"^MP-\d+$", c[0]):
            rows.append((c[0], c[1], c[2]))
    return rows

def main(run_dir):
    aliases, never = load_aliases()
    pipeline = load_pipeline()
    models = {}
    missing = []
    for d in sorted(os.listdir(run_dir)):
        sub = os.path.join(run_dir, d)
        if not os.path.isdir(sub):
            continue
        f = [x for x in os.listdir(sub) if x.startswith("FINDINGS_") and x.endswith(".md")]
        if f:
            models[d] = parse_findings(os.path.join(sub, f[0]))
        else:
            missing.append(d)

    if not models:
        print("No FINDINGS files. If the run is still in flight, wait: a missing file is only "
              "missing once the process has exited.")
        return 1

    # entity -> model -> findings ; and the domains behind it
    ent = collections.defaultdict(lambda: collections.defaultdict(list))
    matched_flag, proposals = {}, collections.defaultdict(set)
    for m, fs in models.items():
        for f in fs:
            key, hit = canon(f["name"], aliases)
            ent[key][m].append(f)
            matched_flag[key] = hit
            if not hit:
                z = zh(f["name"])
                if z:
                    proposals[z[:4]].add((m, f["name"]))

    lines = []
    W = lines.append
    run_id = os.path.basename(run_dir.rstrip("/\\"))
    W(f"# Reconciled panel · {run_id}\n")
    W("Generated by `reconcile.py` in the main system. Not written by the arm, not authoritative for "
      "scoring: gates and scores are `modes/intake.md`.\n")
    W("## Models\n")
    W("| Model dir | Findings | Distinct source domains |")
    W("|---|---|---|")
    for m, fs in models.items():
        doms = {urlparse(u).netloc for f in fs for u in f["urls"] if urlparse(u).netloc}
        W(f"| `{m}` | {len(fs)} | {len(doms)} |")
    for m in missing:
        W(f"| `{m}` | **MISSING** | 0 |")
    W("")

    n_models = len(models)
    W(f"## Entities · {len(ent)} after alias merge, "
      f"{sum(len(fs) for fs in models.values())} raw headings\n")
    W("`models` is how many models saw it. `domains` is how many distinct source domains stand behind it. "
      "**Only `domains` is evidence.** An entity with models=3 and domains=1 is one press article read three "
      "times (CAL-11).\n")
    W("| Entity | models | domains | corroboration | pipeline | alias |")
    W("|---|---|---|---|---|---|")
    rows = []
    for key, per in ent.items():
        doms = {urlparse(u).netloc.replace("www.", "")
                for fs in per.values() for f in fs for u in f["urls"] if urlparse(u).netloc}
        pm = ""
        kz = zh(key)
        for pid, pen, pzh in pipeline:
            if (kz and pzh and (kz[:4] in pzh or pzh[:4] in kz)) or \
               (pen and len(pen) > 4 and pen.lower() in key.lower()):
                pm = f"**{pid}**"
                break
        if len(doms) >= 3:
            corr = "corroborated"
        elif len(doms) == 2:
            corr = "weak"
        else:
            corr = "**single-source**"
        rows.append((len(per), len(doms), key, corr, pm, "yes" if matched_flag.get(key) else "unmatched"))
    for nm, nd, key, corr, pm, al in sorted(rows, key=lambda r: (-r[0], -r[1], r[2])):
        W(f"| {key} | {nm}/{n_models} | {nd} | {corr} | {pm} | {al} |")
    W("")

    single = [r for r in rows if r[1] <= 1 and r[0] >= 2]
    W("## Convergence trap\n")
    if single:
        W("Seen by two or more models but standing on one source domain or none. These look corroborated "
          "and are not. Do not present them as verified.\n")
        for nm, nd, key, *_ in sorted(single, key=lambda r: -r[0]):
            W(f"- {key} · {nm} models · {nd} domain")
    else:
        W("None. Every multi-model entity has at least two distinct source domains.")
    W("")

    W("## Pipeline cross-match\n")
    hits = [r for r in rows if r[4]]
    if hits:
        for nm, nd, key, corr, pm, al in hits:
            W(f"- {key} matches {pm}. This is an UPDATE, not a new row.")
    else:
        W("No entity in this run matches an existing pipeline row.")
    W("")

    W("## Verification queue for 互动易 (irm.cninfo.com.cn)\n")
    W("Listed entities found in this run. 互动易 term search verifies what a listed company declares and, "
      "more usefully, what it does not. Zero records for a term is evidence there; zero results on a search "
      "engine is not.\n")
    listed = sorted({key for key, per in ent.items()
                     for fs in per.values() for f in fs
                     if "listed" in f["fields"].get("entity_type", "").lower()})
    for k in listed:
        W(f"- [ ] {k}")
    if not listed:
        W("- (no entity was labelled `listed company` in this run)")
    W("")

    W("## Proposed new aliases\n")
    W("Unmatched headings sharing a Chinese prefix across models. **Proposals, not merges.** Confirm, then "
      "add to `alias_store.json` so the next run resolves them mechanically.\n")
    any_p = False
    for pref, s in sorted(proposals.items()):
        if len({m for m, _ in s}) >= 2:
            any_p = True
            W(f"- `{pref}` seen as: " + " · ".join(f"{n} ({m})" for m, n in sorted(s)))
    if not any_p:
        W("- none")
    W("")

    # --- Client rubric coverage (the internal client 2026-08-25, wired in 2026-09-04) -------------
    # Three-way on purpose. "absent" is a method failure (nobody searched), "not obtained"
    # is a finding about Chinese disclosure. Collapsing them is how an empty column starts
    # looking like a broken system instead of a measurement.
    RUBRIC = ["forestry_track_record", "traction", "business_model", "differentiators",
              "comparable_direct", "comparable_indirect"]
    EMPTY = ("not obtained", "not searched", "no obtenido", "none", "n/a", "-")

    W("## Client rubric coverage\n")
    W("The six fields the committee filters on. **`absent` is not the same as `not obtained`.** A field the "
      "model omitted means nobody searched, and it is a method failure to fix in the tasking. A field marked "
      "`not obtained` after its Chinese formulations means the information is not public, and that is a "
      "reportable finding. Only the second one may travel to headquarters as an empty cell.\n")
    W("| Rubric field | sourced | not obtained | absent | fill rate |")
    W("|---|---|---|---|---|")
    all_f = [f for fs in models.values() for f in fs]
    total = len(all_f) or 1
    rubric_absent = 0
    for r in RUBRIC:
        sourced = no = absent = 0
        for f in all_f:
            val = f["fields"].get(r, "").strip().lower()
            if r not in f["fields"]:
                absent += 1
            elif val == "" or val.startswith(EMPTY):
                no += 1
            else:
                sourced += 1
        rubric_absent += absent
        W(f"| {r} | {sourced} | {no} | {absent} | {round(100*sourced/total)}% |")
    W("")
    if rubric_absent:
        W(f"**{rubric_absent} field slots were omitted rather than answered.** Before blaming Chinese "
          f"disclosure, check that the tasking carried the formulation table and that the model ran it.\n")

    W("## Contract compliance\n")
    req = ["entity_type", "pipeline_match", "scale_operating", "scale_announced",
           "capital_registered", "financing_verified", "trl_declared",
           "comparable_direct", "comparable_indirect", "sources"]
    W("| Model | " + " | ".join(req) + " |")
    W("|---" * (len(req) + 1) + "|")
    for m, fs in models.items():
        cells = [str(sum(1 for f in fs if r in f["fields"])) + f"/{len(fs)}" for r in req]
        W(f"| `{m}` | " + " | ".join(cells) + " |")
    W("")

    out = os.path.join(run_dir, "RECONCILED.md")
    open(out, "w", encoding="utf-8").write("\n".join(lines))
    print(f"wrote {out}")

    # ---- COMPARISON.md ---------------------------------------------------
    # Written HERE, not by a launcher. The reconciler is the only component every
    # backend shares, so a per-seat comparison produced by the launcher would not
    # exist for a backend that has no launcher (claude-subagents, single-model),
    # while every mode downstream reads this file. Seat accounting belongs to the
    # component that sees all the seats.
    run_id = os.path.basename(os.path.normpath(run_dir))
    seats = sorted(set(list(models.keys()) + list(missing)))
    C = []
    A = C.append
    A(f"# Panel run {run_id}")
    A("")
    A(f"Seats: {len(seats)}   wrote: {len(models)}   MISSING: {len(missing)}")
    A("")
    A("| Seat | Status | Output file | Bytes | Findings | Sourced claims | Duplicates of pipeline | Unique to this seat | Fabrications caught |")
    A("|---|---|---|---|---|---|---|---|---|")
    for s in seats:
        d = os.path.join(run_dir, s)
        f = None
        if os.path.isdir(d):
            cand = sorted(x for x in os.listdir(d) if x.startswith("FINDINGS_") and x.endswith(".md"))
            if cand:
                f = os.path.join(d, cand[0])
        if f and os.path.exists(f):
            body = open(f, encoding="utf-8").read()
            n = len(models.get(s, []))
            uniq = sum(1 for e, ms in ent.items() if list(ms) == [s]) if isinstance(ent, dict) else ""
            A(f"| `{s}` | ok | `{s}/{os.path.basename(f)}` | {len(body.encode())} | {n} | | | {uniq} | |")
        else:
            why = "ran, wrote nothing" if os.path.isdir(d) else "killed or never finished"
            A(f"| `{s}` | **MISSING** ({why}) | | 0 | 0 | | | 0 | |")
    A("")
    A(f"Distinct entities after alias merge: {len(ent)}")
    A(f"Single-source entities (one distinct source domain, no matter how many seats agreed): {len(single)}")
    A("")
    A("Columns beyond Findings are filled by the main system during intake, never by the arm.")
    A("A seat that produced zero findings is a data point about that seat, not an empty week.")
    A("A row marked MISSING is a FAILED RUN, not an empty result. Check the seat directory and its transcript first.")
    A("Model agreement is not corroboration: independence is the distinct-source-domain count above.")
    A("")
    comp = os.path.join(run_dir, "COMPARISON.md")
    open(comp, "w", encoding="utf-8").write("\n".join(C))
    print(f"wrote {comp}")
    print(f"  models with output : {len(models)}   missing: {len(missing)}")
    print(f"  raw headings       : {sum(len(fs) for fs in models.values())}")
    print(f"  entities after merge: {len(ent)}")
    print(f"  single-source traps : {len(single)}")
    print(f"  pipeline matches    : {len(hits)}")
    return 0

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
